on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test pack
    steps:
      - uses: actions/checkout@v1
      - name: Setup rclone
        id: hello
        uses: ./
      - run: rclone --help
